# Generated by Django 2.2.1 on 2019-05-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafiostone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='idade',
            field=models.IntegerField(max_length=2),
        ),
    ]
