# Generated by Django 2.2.1 on 2019-05-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafiostone', '0003_auto_20190530_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
